careerme/main/routes.py
from flask import Blueprint,render_template , request
from careerme.models import JobListing
from careerme import db , app


main = Blueprint('main',__name__)

locations_to_count = ['budapest','madrid','istanbul','copenhagen']

@main.route("/")
@main.route("/index")
def home():
    jobs=JobListing.query.order_by(JobListing.posted_time.desc()).all()
    location_counts = {location: JobListing.query.filter_by(location=location).count() for location in locations_to_count}
    return render_template('index.html',jobs=jobs,location_counts=location_counts)

@main.route("/about")
def about():
    return render_template('about.html',title="About Page")

@main.route("/contact")
def contact():
    return render_template('contact.html',title="Contact Page")


@main.route("/search" , methods=['POST'])
def search():
    search_term=request.form.get('search_term', '').lower()
    results= JobListing.query.filter(db.func.lower(JobListing.title).contains(search_term)).all()
    print(search_term)
    return render_template('search-results.html',results=results, search_term=search_term)

careerme/user/routes.py
import os
import secrets
from PIL import Image
from flask import Blueprint,render_template,redirect,flash,url_for , request , abort
from careerme.forms import (RegisterCompany,RegisterUser,LoginForm , JobAddForm , EditForm , CVForm)
from careerme.models import Company , Worker , JobListing , CV , Education,Skill,Contact
from careerme import bcrypt , db , app, login_manager
from flask_login import login_user , current_user,logout_user,login_required

user = Blueprint('user',__name__)

job_types = {
        'fulltime': 'Full Time',
        'parttime': 'Part Time',
        'Contract': 'Contract' }

@user.route("/register", methods=['GET', 'POST'])
def register():
    userform = RegisterUser()
    companyform = RegisterCompany()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if companyform.submitRC.data and companyform.validate():
        if companyform.validate_on_submit():
            pw_hash = bcrypt.generate_password_hash(companyform.password.data).decode('utf-8')
            addnewcompany = Company(company_name=companyform.companyname.data,company_email=companyform.email.data,password=pw_hash,company_detail=companyform.companyinfo.data)
            db.session.add(addnewcompany)
            db.session.commit()
            flash(f'Company Name: "{companyform.companyname.data}" Successfully registered!', 'success')
            return redirect(url_for('user.login'))
    if userform.submitRU.data and userform.validate():
        if userform.validate_on_submit():
            pw_hash = bcrypt.generate_password_hash(userform.password.data).decode('utf-8')
            addnewworker = Worker(worker_fullname=userform.fullname.data,worker_email=userform.email.data,password=pw_hash)
            db.session.add(addnewworker)
            db.session.commit()
            flash(f'User : {userform.fullname.data} Successfully registered!', 'success')
            return redirect(url_for('user.login'))
    return render_template('register.html',title='Register',userform=userform,companyform=companyform)


@user.route("/login" , methods=['GET', 'POST'])
def login():
    form = LoginForm()
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    if form.validate_on_submit():
        company_user = Company.query.filter_by(company_email=form.email.data).first()
        if company_user is None:
            user = Worker.query.filter_by(worker_email=form.email.data).first()
        else:
            user = company_user

        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user)
            flash('Login successful!', 'success')
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check username and password', 'danger')
    return render_template('login.html', title="Login", form=form)

@user.route('/logout')
def logout():
    if current_user.is_authenticated:
        logout_user()
        return redirect(url_for('main.home'))
    else:
        flash('You have not login yet!!', 'info') 
        return redirect(url_for('user.register'))


@user.route('/account' , methods=['GET', 'POST'])
@login_required
def account():
    company_id_to_query = current_user.id
    job_listings = JobListing.query.order_by(JobListing.posted_time.desc()).filter_by(company_id=company_id_to_query).all()
    show_cv_list = CV.query.filter_by(worker_id=current_user.id).all()   
    if show_cv_list:
        for show_cv in show_cv_list:
            educations = Education.query.filter_by(cv_id=show_cv.id).all()
            skills = Skill.query.filter_by(cv_id=show_cv.id).all()
            contact = Contact.query.filter_by(cv_id=show_cv.id).first()
    else:
        educations = 0
        skills = 0
        contact = 0
    for job_listing in job_listings:
        job_listing.posted_time_str = job_listing.posted_time.strftime('%d/%m/%Y %H:%M')
    form = JobAddForm()
    if request.method == 'POST':
        if form.validate_on_submit:
            jobtype = request.form.get('job_type')
            postnewjob = JobListing(title=form.jobtitle.data,job_type=jobtype
                                    ,content=form.jobdescription.data,
                                    location=form.joblocation.data,company=current_user)
            db.session.add(postnewjob)
            db.session.commit()
            flash(f'You added new job!', 'success')
            return redirect(url_for('main.home'))
    return render_template('account.html', title="My Account" , form=form , 
                           job_types=job_types,job_listings = job_listings , show_cv_list = show_cv_list , educations = educations , skills=skills,contact=contact)


@user.route("/list/<int:list_id>" , methods=['GET', 'POST'])
def post(list_id):
    list = JobListing.query.get_or_404(list_id)
    form = JobAddForm()
    jobtype = request.form.get('job_type')
    if request.method == 'POST':
        if list.company != current_user:
            abort(403)
        if form.validate_on_submit:
            list.title = form.jobtitle.data
            list.content = form.jobdescription.data
            list.location = form.joblocation.data
            db.session.commit()
            flash(f'You updated your listing!', 'success')
            return redirect(url_for('user.account'))
    elif request.method == 'GET':
        form.jobtitle.data = list.title
        form.jobdescription.data = list.content
        form.joblocation.data = list.location
    return render_template('list.html', title=list.title, list=list , form=form , job_types=job_types)

@user.route("/list/<int:list_id>/delete" , methods=['GET','POST'])
@login_required
def delete(list_id):
    list = JobListing.query.get_or_404(list_id)
    if list.company != current_user:
         return redirect(url_for('user.login'))
         abort(403)
    db.session.delete(list)
    db.session.commit()
    flash(f'You have succesfully delete your listing!', 'warning')
    return redirect(url_for('user.account'))



def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(app.root_path, 'static/profile_pics', picture_fn)

    output_size = (250, 250)
    i = Image.open(form_picture)
    i.thumbnail(output_size)
    i.save(picture_path)

    return picture_fn


@user.route("/edit" , methods=['GET', 'POST'])
@login_required
def edit():
    form = EditForm()
    if form.validate_on_submit():
            if form.newphoto.data:
                picture_file = save_picture(form.newphoto.data)
                current_user.company_photo = picture_file 
            current_user.company_name = form.newname.data
            current_user.company_detail = form.newabout.data
            db.session.commit()
            flash(f'Successfully Updated!','success')
            return redirect(url_for('user.account'))
    elif request.method == 'GET':
        form.newname.data = current_user.company_name
        form.newabout.data = current_user.company_detail
    
    image_file = url_for('static', filename='profile_pics/' + current_user.company_photo)
    return render_template('edit.html',title='Update Profile',form=form,image_file=image_file)



@user.route("/create-cv", methods=['GET','POST'])
@login_required
def createcv():
    form = CVForm()
    if request.method =='POST':
        if form.validate_on_submit:
            create_cv = CV(
                worker_id = current_user.id,
                educations=[Education(degree=form.degree.data,
                                    school=form.school.data,
                                    starting_year=form.starting_year.data,
                                    graduation_year=form.graduation_year.data)],
                skills=[Skill(skill_name=form.skills.data)],
                contact=(Contact(phone=form.phone.data,
                                email=form.email.data,
                                location=form.location.data)))
                
            db.session.add(create_cv)
            db.session.commit()
            flash(f'Successfully Added!','success')
            return redirect(url_for('user.account'))
    return render_template('create-cv.html',title='Cv Create',form=form)



   

careerme/templates/about.html
{% extends "base.html" %}
{% block content %}
<section>
    <div class="container">
        <h2 class="text-center mb-4">About Us</h2>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed tincidunt libero sit amet quam tincidunt, non mattis dui finibus. Ut congue, metus eget euismod suscipit, tellus ligula fermentum metus, non pharetra orci lacus a ex. Nunc nec augue ac justo pharetra venenatis. Vestibulum efficitur tincidunt justo, ac malesuada odio bibendum ut. Duis vestibulum urna nec magna laoreet cursus. Aliquam erat volutpat. In hac habitasse platea dictumst.</p>
        <p>Job finding in our website is made easy with our user-friendly platform. We strive to connect employers with qualified candidates, making the hiring process efficient and effective. Whether you are a job seeker or an employer, we are here to help you find the right match.</p>
    </div>
</section>

<section class="features-section bg-light">
    <div class="container">
        <h2 class="text-center mb-4">Our Features</h2>
        <div class="row">
            <div class="col-md-4">
                <div class="feature-card">
                    <i class="fas fa-search feature-icon"></i>
                    <h4>As a worker</h4>
                <p>You can find your dream job in few clicks!</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="feature-card">
                    <i class="fas fa-users feature-icon"></i>
                    <h4>As a company</h4>
                <p>Find your best employers. Very easy and easy to follow!</p>
                </div>
            </div>
            <div class="col-md-4">
                <div class="feature-card">
                    <i class="fas fa-check-circle feature-icon"></i>
                    <h4>Totally FREE!</h4>
                <p>Hire or Hired, totally free. We are not asking any money for listing.</p>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}

careerme/templates/account.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <div class="profile-container">
        <div class="left-column">
            {% if current_user.company_name %}
            <div class="profile-picture">
                <img style="border-radius: 50%;" src="{{ url_for('static', filename='profile_pics/' + current_user.company_photo)}}">
            </div>
            <div>Company</div>
            <div class="username">{{ current_user.company_name }}</div>
            <div class="location">{{ current_user.company_email }}</div>
            {% elif current_user.worker_fullname %}
            <div class="profile-picture">
                <img style="border-radius: 50%; width: 100%;" src="{{ url_for('static', filename='profile_pics/default.jpg')}}">
            </div>       
            <div>Candidate</div>
            <div class="username">{{ current_user.worker_fullname }}</div>
            <div class="location">{{ current_user.worker_email }}</div>
            {%  endif %}
        </div>

        <div class="right-column">
            {% if current_user.company_name %}
            <div class="about-me-section">
                <h3>About Us</h3>
                <p>{{ current_user.company_detail }}</p>
            </div>
            {% elif current_user.worker_fullname %}
            <div class="about-me-section">
                <h3>About Me</h3>
                <p>{{ current_user.about }}</p>
            </div>
            
            <div class="update-section">
                {% if show_cv %}
                <a class="btn btn-primary button" href="{{ url_for('user.createcv')}}">Update CV</a>
                {% else %}
                <a class="btn btn-primary button" href="{{ url_for('user.createcv')}}">Create CV</a>
                {%  endif %}
                <button class="btn btn-primary button" data-toggle="modal">Update Profile</button>
                {%  endif %}{% if current_user.company_name %}
                <a class="btn btn-primary button" href="{{ url_for('user.edit')}}">Update Profile</a>
                <button class="btn btn-primary button" data-toggle="modal" onclick="showModalBody()">Add Listing</button>
                {%  endif %}
            </div>
            {% if current_user.worker_fullname %}
            
        </div>{%  endif %}
    </div>
</div>
{% if current_user.company_name %}
<section>
    <div class="container">
        <h2>Our Job Offers</h2>
        <div class="row listing-section">
            {% for job in job_listings %}
            <div class="col-md-6">
                <div class="my-listing-card">
                    <div class="my-listing-info">
                        <div>
                            <p><strong>Date:</strong> {{ job.posted_time_str }}</p>
                            <p><strong>Title:</strong> {{ job.title }}</p>
                            <p><strong>Details:</strong> {{ job.content[:150]}}</p>
                        </div>
                        <a class="my-view-btn" href="{{ url_for('user.post', list_id=job.id) }}">View</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>
{% elif current_user.worker_fullname %}                    
{% if show_cv_list %}
<div class="container mt-4">
    <section>
        <h2 class="mb-4">{{ current_user.worker_fullname }}</h2>
        <hr class="my-4">
        <div class="mb-4">
            <h3>Education</h3>
        <div class="row">
        {% for show_cv in show_cv_list %}
        {% for education in show_cv.educations %}
        <div class="col-md-6">
                <h5>{{ education.school }}</h5>    
                <p>Major:{{ education.degree }}<br>
                ({{ education.starting_year }} - {{ education.graduation_year }})</p>
        </div>
        {% endfor %}
        {% endfor %}
    </div> 
    
    {% else %}
        <p>No CV found.</p>
    {% endif %}
{% endif %}
</section>
</div>            
{% endblock %}

careerme/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% if title %}
    <title>Career Me - {{ title }}</title>
        {% else %}
    <title>Career Me</title>
    {% endif %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Lato:wght@400;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.2/css/all.min.css">
    <link href="{{ url_for('static', filename='listpost.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='main.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='cv.css') }}" rel="stylesheet">{% if title == "My Account" %}
    <link href="{{ url_for('static', filename='my-account.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='listing.js') }}" rel="stylesheet">
    {% endif %}
</head>
<body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top">
        <div class="container">
            <h1 class="navbar-brand"><a class="navbarlink"href="{{ url_for('main.home')}}">Career Me!</a></h1>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end" id="navbarNav">
                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.about')}}">About Us</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('main.contact')}}">Contact</a>
                    </li>
                    {% if current_user.is_authenticated %} 
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.account')}}">My Account</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.logout')}}">Logout</a>
                    </li>
                    {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.register')}}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('user.login')}}">Login</a>
                    </li>
                    {%  endif %}

                </ul>
            </div>
        </div>
    </nav>
    {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
              {% for category, message in messages %}
    <div class="text-center alert alert-{{category}}" role="alert">
        {{ message }}
      </div>
      {% endfor %}
    {% endif %}
    {% endwith %}

{% block content %}
{% endblock %}

<footer>
    <p>&copy; Made in 2024. All Rights Reserved. | <a href="https://github.com/neymaro" target="_blank">github.com/neymaro</a></p>
</footer>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

careerme/templates/contact.html
{% extends "base.html" %}
{% block content %}

<div class="container mt-5">
    <h2>Contact Us</h2>

    <div class="row mt-4">
        <div class="col-md-6">
            <h4>Social Media</h4>
            <ul class="list-unstyled">
                <li><i class="fab fa-facebook"></i> <a href="https://www.facebook.com/">Facebook</a></li>
                <li><i class="fab fa-twitter"></i> <a href="https://twitter.com/">Twitter</a></li>
                <li><i class="fab fa-instagram"></i> <a href="https://www.instagram.com/">Instagram</a></li>
                <!-- Add more social media links as needed -->
            </ul>
        </div>

        <div class="col-md-6">
            <h4>Opening Hours</h4>
            <p>Monday - Friday: 9:00 AM - 6:00 PM</p>
            <p>Saturday: 10:00 AM - 4:00 PM</p>
            <p>Sunday: Closed</p>
        </div>
    </div>

    <div class="row mt-4">
        <div class="col-md-6">
            <h4>Location</h4>
            <p>Budapest , HUNGARY</p>
        </div>

        <div class="col-md-6">
            <h4>Additional Information</h4>
            <p>Email: info@example.com</p>
            <p>Phone: +1 (123) 456-7890</p>
        </div>
    </div>
</div>
{% endblock %}

careerme/templates/edit.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-5">
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <div class="card">
                <div class="card-header">
                    <h5 class="mb-0">User Profile</h5>
                </div>
                <div class="card-body">

                    <!-- Overview Section -->
                    <div class="mb-4">
                        <h6>Overview</h6>
                        <p>{{current_user.company_name}} , {{current_user.company_email}}  {{current_user.company_details}}</p>
                    </div>

                    <!-- Input Fields -->
                    <form method="POST" action="" enctype="multipart/form-data">
                        {{ form.hidden_tag()}}
                        <div class="form-group">
                            {{ form.newname.label(class="form-control-label" , for="fullName") }}
                            {% if form.newname.errors %}
                            {{ form.newname(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.newname.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                                </div>
                            {% else %}
                                {{ form.newname(class="form-control",placeholder="Enter title of job") }}
                            {% endif %}
                        </div>
                
                        {{ form.newphoto.label( class="form-control-file" ,id="changePhoto") }}
                        {% if form.newphoto.errors %}
                            {{form.newphoto(class="form-input is-invalid")}}
                                {% for error in form.newphoto.errors %}
                                <span>{{ error }}</span>
                                {% endfor %}
                        {% else%}
                            {{form.newphoto(class="form-input")}}  
                        {% endif %}

                        <div class="form-group">
                            {{ form.newabout.label(class="form-control-label" , for="fullName") }}
                            {% if form.newabout.errors %}
                            {{ form.newabout(class="form-control is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.newabout.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                                </div>
                            {% else %}
                                {{ form.newabout(class="form-control",placeholder="Enter title of job") }}
                            {% endif %}
                        </div>

                        
                        <div class="form-group">
                            {{ form.submit(class="btn btn-primary",value="Update") }}
                        </div>
                    </form>

                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

careerme/templates/index.html
{% extends "base.html" %}
{% block content %}
<section>
    <div class="container">
        <div class="row">
            <div class="col-md-6 offset-md-3 text-center">
                <h2>Find Your Dream Job!</h2>
                <p>Write any title that you might be interested in!</p>
                <form class="search-form" action="/search" method="post" >
                    <div class="input-group">
                        <input type="text" class="form-control" placeholder="Job Title" aria-label="Search" name="search_term">
                        <div class="input-group-append">
                            <button class="btn btn-primary" type="submit" id="button-addon2">Find!</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</section>

<section class="section">
    <div class="container">
        <div class="row md-m-25px-b m-45px-b justify-content-center text-center">
            <div class="col-lg-8">
                <h3 class="h1 m-15px-b">Latest Job Positions</h3>
                <p class="m-0px font-2">You can find active job offers here.</p>
            </div>
        </div>
        
        <div class="row">
            {% for job in jobs %}
            <div class="col-sm-6 col-lg-4 m-15px-tb">
                <div class="media box-shadow-only-hover hover-top border-all-1 border-color-gray p-15px">
                    <div class="icon-50 theme-bg white-color border-radius-50 d-inline-block">
                        <img src="{{ url_for('static', filename='profile_pics/' + job.company.company_photo)}}" style="width: 50px; height: 50px; border-radius: 70%;object-fit: cover;" class="company-logo">
                    </div>
                    
                    <div class="p-20px-l media-body">
                        <span class="theme2nd-bg white-color p-0px-tb p-10px-lr font-small border-radius-15">{{job.job_type}}</span>
                        <h6>
                            <a href="{{ url_for('user.post', list_id=job.id) }}">{{ job.title }}</a>
                        </h6>
                        <p class="m-0px font-small" style="text-transform: capitalize;">{{job.location}}</p>
                    </div>
                </div>
            </div>
            
            {% endfor %}
            <div class="col-12 p-25px-t text-center">
                <a class="m-btn m-btn-radius m-btn-theme" href="#">Load More</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

careerme/templates/list.html
{% extends "base.html" %}
{% block content %}
<br>
<div class="container job-container">
    <div class="row">
      <div class="col-md-8 job-details">
        <h2>{{ list.title }}</h2>
        <p style="text-transform: capitalize;"><strong>Location:</strong> {{ list.location }}</p>
        <p><strong>Job Type:</strong> {{ list.job_type }}</p>
        <h5>Description:</h5>
        <p>{{ list.content }}</p>
        {% if list.company == current_user %}
        <div class="text-right">
          <button class="btn btn-primary" data-toggle="modal" data-target="#updateModal">Update</button>
          <button class="btn btn-danger" onclick="confirmDelete()">Delete</button>
        </div>
        {% endif %}
      </div>
      <div class="col-md-4 company-sidebar">
        <img src="{{ url_for('static', filename='profile_pics/' + list.company.company_photo)}}" style="width: 150px;height: 150px;border-radius: 20%;" class="company-logo">
        <div class="company-details">
          <h4>Company Details</h4>
          <p><strong>Company Name:</strong> {{ list.company.company_name }}</p>
          <p><strong>Detail:</strong> {{ list.company.company_detail }}</p>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Update Modal -->
  <div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="updateModalLabel" method="GET">Update Job Details</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <!-- Update form with fields for each detail -->
          <form method="POST">
            <div class="form-group">
              <label for="updatedTitle">Job Title:</label>
              {{ form.jobtitle(class="form-control") }}          
            </div>
            <div class="form-group">
              <label for="updatedLocation">Location:</label>
              {{ form.joblocation(class="form-control") }} 
            </div>
            <div class="form-group">
                {{ form.jobtype.label(class="form-control-label" , for="fullName") }}<br>
                <div class="form-check form-check-inline">
                    {% for key,value in job_types.items() %}
                    {{ form.jobtype(class="mr-1",type="radio" , value="{{ key }}") }} {{ value }}<br class="mr-2">
                    <p style="margin-right: 5px;"></p>
                {% endfor %}
                </div> 
            </div>
            <div class="form-group">
              <label for="updatedDescription">Description:</label>
              {{ form.jobdescription(class="form-control") }} 
            </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          {{ form.submit(class="btn btn-primary",value="UPDATE") }}
        </div>
    </form>
      </div>
    </div>
  </div>
  
  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.0.8/dist/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
  <script>
    function confirmDelete() {
      if (confirm("Are you sure you want to delete this job?")) {
        window.location='{{ url_for('user.delete', list_id=list.id) }}'
      } else {
        
      }
    }
  
  </script>
{% endblock %}

careerme/templates/search-results.html
{% extends "base.html" %}
{% block content %}
<div class="container mt-5">
    <h1>Search Results for '{{ search_term }}'</h1>

    {% if results %}
        <ul class="list-group">
            {% for job in results %}
                <li class="list-group-item"><a href="{{ url_for('user.post', list_id=job.id) }}">{{ job.title }}</a></li>
            {% endfor %}
        </ul>
    {% else %}
        <p>No results found.</p>
    {% endif %}

    <a href="{{ url_for('main.home')}}" class="btn btn-primary mt-3">Back to All Jobs</a>
</div>

{% endblock %}